import { Translation } from './types';

export const DICTIONARY: Record<string, Translation> = {
  en: {
    title: "Meta Tag Fixer",
    tagline: "AI-Powered Meta Tag Generator for Better SEO",
    inputPlaceholder: "Paste your article, blog post, or webpage content here to generate SEO tags...",
    generateMeta: "Generate Meta Tags",
    generateHtml: "Generate HTML Code",
    analyzing: "AI Analyzing Content...",
    results: "Analysis Results",
    tabMeta: "Meta Tags",
    tabHtml: "HTML Code",
    tabKeywords: "Keywords",
    tabScore: "SEO Score",
    copy: "Copy",
    copied: "Copied!",
    downloadJson: "Export JSON",
    downloadTxt: "Export TXT",
    keywordsPrimary: "Primary Keywords",
    keywordsSecondary: "Secondary Keywords",
    keywordsLongTail: "Long-tail Keywords",
    scoreTitle: "Content Readiness Score",
    scoreGood: "Excellent",
    scoreAverage: "Needs Improvement",
    scorePoor: "Poor",
    tipsTitle: "Improvement Suggestions",
    clear: "Clear All",
    errorEmpty: "Please enter some text to analyze.",
    errorApi: "Failed to generate data. Please try again.",
  },
  bn: {
    title: "মেটা ট্যাগ ফিক্সার",
    tagline: "উন্নত এসইও-এর জন্য এআই চালিত মেটা ট্যাগ জেনারেটর",
    inputPlaceholder: "এসইও ট্যাগ তৈরি করতে আপনার আর্টিকেল, ব্লগ পোস্ট বা ওয়েবপেজের বিষয়বস্তু এখানে পেস্ট করুন...",
    generateMeta: "মেটা ট্যাগ তৈরি করুন",
    generateHtml: "HTML কোড তৈরি করুন",
    analyzing: "এআই বিশ্লেষণ করছে...",
    results: "বিশ্লেষণের ফলাফল",
    tabMeta: "মেটা ট্যাগ",
    tabHtml: "HTML কোড",
    tabKeywords: "কিওয়ার্ডস",
    tabScore: "এসইও স্কোর",
    copy: "কপি",
    copied: "কপি হয়েছে!",
    downloadJson: "JSON ডাউনলোড",
    downloadTxt: "TXT ডাউনলোড",
    keywordsPrimary: "প্রধান কিওয়ার্ড",
    keywordsSecondary: "সহায়ক কিওয়ার্ড",
    keywordsLongTail: "লং-টেইল কিওয়ার্ড",
    scoreTitle: "বিষয়বস্তু প্রস্তুতির স্কোর",
    scoreGood: "চমৎকার",
    scoreAverage: "উন্নতি প্রয়োজন",
    scorePoor: "দুর্বল",
    tipsTitle: "উন্নতির পরামর্শ",
    clear: "মুছে ফেলুন",
    errorEmpty: "অনুগ্রহ করে বিশ্লেষণের জন্য কিছু লেখা দিন।",
    errorApi: "ডেটা তৈরি করতে ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
  }
};

export const INITIAL_SEO_DATA = {
  title: "",
  description: "",
  keywords: [],
  robots: "index, follow",
  author: "",
  score: 0,
  tips: [],
  keywordsDetailed: {
    primary: [],
    secondary: [],
    longTail: []
  }
};